version: "3"

services:
  ethereum:
    image: plainchant/ethereum:golang
    build:
      ./
    container_name: ethereum_private
#    volumes:
#      - ./ethereum:/ethereum/
    ports:
      - 8555:8545
      - 30304:30303
    command: geth --networkid 13141 --datadir /ethereum --rpc --rpcapi db,eth,net,web3,personal