version: "3"

services:
  ethereum:
    image: plainchant/ethereum:golang
    build:
      ./
    container_name: eos_docker_tools
    volumes:
      - ./ethereum:/ethereum
    ports:
      - 8555:8545
      - 30304:30303
      - 30304/udp:30303/udp
    command: geth init /ethereum/genesis.json && geth --networkid 13141 --datadir /ethereum --rpc --rpcapi db,eth,net,web3,personal
