version: "3"

services:
  ethereum:
    image: plainchant/ethereum:golang
    build:
      ./
    container_name: eos_docker_tools
    volumes:
      - ./:/ethereum
    ports:
      - 8555:8545
    expose:
      - 30303
      - 30303/udp
