version: "3"

services:
  ethereum:
    image: plainchant/ethereum:golang
    build:
      ./
    container_name: eos_docker_tools
    ports:
      - 8545:8545
    expose:
      - 30303
      - 30303/udp
